
BLENDER="C:\Program Files\Blender Foundation\Blender 5.2.1\blender.exe"
DIST=../dist

all : \
    $(DIST)/burger.pnct \
    $(DIST)/burger.scene \

$(DIST)/burger.scene : burger.blend export-scene.py
	$(BLENDER) --background --python export-scene.py -- "burger.blend:Main" "$(DIST)/burger.scene"

$(DIST)/burger.pnct : burger.blend export-meshes.py
	$(BLENDER) --background --python export-meshes.py -- "burger.blend:Main" "$(DIST)/burger.pnct"
